### ISSUE TITLE
[github-tf] Output were not created 

### ISSUE THREAD

**Issue by tuannvm** [honestbee/devops-tools#4]
I ran into this issue:
- Firstly, I built the package, tried to run, and all the templates were generated successfully
- I deleted `outputs/` folder, tried to run again, and nothing happen, silent exit.
- Ran with `debug` mode resulted in the same issue.
```
DEBU[0001] GitHub Response Code: 200

DEBU[0001] GitHub Rate Remaining: 4802

DEBU[0001] GitHub Response Code: 200

DEBU[0001] GitHub Rate Remaining: 4801

DEBU[0002] GitHub Response Code: 200

DEBU[0002] GitHub Rate Remaining: 4800
```

- Related PR https://github.com/honestbee/devops-tools/pull/3

**Comment by so0k** [comment]
it is true that my error checks are terrible and everything is swallowed, but I pointed out a mistake in your code
